#!/bin/bash
# Network Setup Script
# Configures network interfaces for distributed deployment
# Requires: sudo privileges for network configuration

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running with sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run with sudo${NC}"
    echo "Usage: sudo $0 [deployment_config]"
    exit 1
fi

# Get deployment configuration
DEPLOYMENT="${1:-local}"
DEPLOYMENT_CONFIG="$REPO_ROOT/config/deployment/${DEPLOYMENT}.yaml"

if [ ! -f "$DEPLOYMENT_CONFIG" ]; then
    echo -e "${RED}Error: Deployment configuration not found: $DEPLOYMENT_CONFIG${NC}"
    exit 1
fi

echo -e "${GREEN}=== Isaac Robot Network Setup ===${NC}"
echo "Deployment: $DEPLOYMENT"
echo "Config: $DEPLOYMENT_CONFIG"
echo ""

# Parse deployment config (requires yq or python-yaml)
if command -v yq &> /dev/null; then
    NETWORK_MODE=$(yq e '.deployment.network.mode' "$DEPLOYMENT_CONFIG")
    REQUIRE_SUDO=$(yq e '.deployment.network.require_sudo' "$DEPLOYMENT_CONFIG")
else
    echo -e "${YELLOW}Warning: yq not found, assuming network mode from deployment type${NC}"
    case "$DEPLOYMENT" in
        local|test|sim)
            NETWORK_MODE="local"
            REQUIRE_SUDO="false"
            ;;
        dual_compute|cloud_dev)
            NETWORK_MODE="distributed"
            REQUIRE_SUDO="true"
            ;;
        *)
            NETWORK_MODE="local"
            REQUIRE_SUDO="false"
            ;;
    esac
fi

echo "Network mode: $NETWORK_MODE"
echo "Requires sudo: $REQUIRE_SUDO"
echo ""

# Check if sudo is required but not provided
if [ "$REQUIRE_SUDO" = "true" ] && [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This deployment requires sudo privileges${NC}"
    exit 1
fi

# Configure network based on mode
case "$NETWORK_MODE" in
    local)
        echo -e "${GREEN}Configuring local network (no changes needed)${NC}"
        echo "Using localhost/multicast discovery"
        ;;
    
    distributed)
        echo -e "${GREEN}Configuring distributed network${NC}"
        
        # Determine host role
        HOSTNAME=$(hostname)
        if [[ "$HOSTNAME" == *"pi"* ]] || [[ "$HOSTNAME" == "isaac-pi" ]]; then
            HOST_ROLE="pi"
            STATIC_IP="192.168.1.10/24"
            INTERFACE="eth0"
        elif [[ "$HOSTNAME" == *"jetson"* ]] || [[ "$HOSTNAME" == "isaac-jetson" ]] || [[ "$HOSTNAME" == "isaac" ]]; then
            HOST_ROLE="jetson"
            STATIC_IP="192.168.1.20/24"
            INTERFACE="eth0"
        else
            echo -e "${YELLOW}Warning: Unknown hostname, using default configuration${NC}"
            HOST_ROLE="unknown"
            STATIC_IP="192.168.1.100/24"
            INTERFACE="eth0"
        fi
        
        echo "Host role: $HOST_ROLE"
        echo "Static IP: $STATIC_IP"
        echo "Interface: $INTERFACE"
        
        # Check if interface exists
        if ! ip link show "$INTERFACE" &> /dev/null; then
            echo -e "${YELLOW}Warning: Interface $INTERFACE not found${NC}"
            echo "Available interfaces:"
            ip link show
            exit 1
        fi
        
        # Configure static IP using netplan (Ubuntu) or NetworkManager
        if [ -d "/etc/netplan" ]; then
            echo "Configuring static IP via netplan..."
            
            NETPLAN_FILE="/etc/netplan/99-isaac-robot.yaml"
            cat > "$NETPLAN_FILE" <<EOF
# Isaac Robot Network Configuration
# Generated by setup_network.sh
network:
  version: 2
  renderer: networkd
  ethernets:
    $INTERFACE:
      addresses:
        - $STATIC_IP
      gateway4: 192.168.1.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
EOF
            
            echo "Applying netplan configuration..."
            netplan apply
            
            echo -e "${GREEN}Static IP configured successfully${NC}"
        else
            echo -e "${YELLOW}Warning: netplan not found, attempting NetworkManager${NC}"
            
            if command -v nmcli &> /dev/null; then
                echo "Configuring static IP via NetworkManager..."
                
                nmcli connection modify "$INTERFACE" ipv4.addresses "$STATIC_IP"
                nmcli connection modify "$INTERFACE" ipv4.gateway "192.168.1.1"
                nmcli connection modify "$INTERFACE" ipv4.dns "8.8.8.8 8.8.4.4"
                nmcli connection modify "$INTERFACE" ipv4.method manual
                nmcli connection up "$INTERFACE"
                
                echo -e "${GREEN}Static IP configured successfully${NC}"
            else
                echo -e "${RED}Error: Neither netplan nor NetworkManager found${NC}"
                exit 1
            fi
        fi
        
        # Configure firewall rules
        echo "Configuring firewall..."
        if command -v ufw &> /dev/null; then
            # Allow ROS 2 DDS traffic
            ufw allow from 192.168.1.0/24 to any port 7400:7500 proto udp comment "ROS 2 DDS"
            ufw allow from 192.168.1.0/24 to any port 11811 proto tcp comment "FastDDS Discovery"
            ufw allow from 192.168.1.0/24 to any port 8765 proto tcp comment "Foxglove Bridge"
            ufw allow from 192.168.1.0/24 to any port 22 proto tcp comment "SSH"
            echo -e "${GREEN}Firewall rules configured${NC}"
        else
            echo -e "${YELLOW}Warning: ufw not found, skipping firewall configuration${NC}"
        fi
        ;;
    
    cloud)
        echo -e "${GREEN}Configuring cloud network${NC}"
        echo "Using FastDDS discovery server with SSH tunnel"
        
        # Note: SSH tunnel setup is handled by launch files
        # This just ensures network is ready
        ;;
    
    *)
        echo -e "${RED}Error: Unknown network mode: $NETWORK_MODE${NC}"
        exit 1
        ;;
esac

# Configure FastDDS environment
echo ""
echo -e "${GREEN}Configuring FastDDS environment${NC}"

# Set ROS_DOMAIN_ID
if command -v yq &> /dev/null; then
    ROS_DOMAIN_ID=$(yq e '.deployment.nodes[].ros_domain_id' "$DEPLOYMENT_CONFIG" | head -1)
else
    case "$DEPLOYMENT" in
        test)
            ROS_DOMAIN_ID=42
            ;;
        sim)
            ROS_DOMAIN_ID=1
            ;;
        *)
            ROS_DOMAIN_ID=0
            ;;
    esac
fi

echo "export ROS_DOMAIN_ID=$ROS_DOMAIN_ID" >> /etc/profile.d/ros2.sh
echo "ROS_DOMAIN_ID set to: $ROS_DOMAIN_ID"

# Configure FastDDS discovery server (if distributed mode)
if [ "$NETWORK_MODE" = "distributed" ] || [ "$NETWORK_MODE" = "cloud" ]; then
    echo "Setting up FastDDS discovery server..."
    
    # Create FastDDS XML config
    FASTDDS_CONFIG="/etc/fastdds.xml"
    cat > "$FASTDDS_CONFIG" <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<dds>
    <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
        <transport_descriptors>
            <transport_descriptor>
                <transport_id>udp_transport</transport_id>
                <type>UDPv4</type>
            </transport_descriptor>
        </transport_descriptors>
        
        <participant profile_name="discovery_server" is_default_profile="true">
            <rtps>
                <builtin>
                    <discovery_config>
                        <discoveryProtocol>SERVER</discoveryProtocol>
                        <discoveryServersList>
                            <RemoteServer prefix="44.53.00.5f.45.50.52.4f.53.49.4d.41">
                                <metatrafficUnicastLocatorList>
                                    <locator>
                                        <udpv4>
                                            <address>192.168.1.20</address>
                                            <port>11811</port>
                                        </udpv4>
                                    </locator>
                                </metatrafficUnicastLocatorList>
                            </RemoteServer>
                        </discoveryServersList>
                    </discovery_config>
                </builtin>
            </rtps>
        </participant>
    </profiles>
</dds>
EOF
    
    echo "export FASTRTPS_DEFAULT_PROFILES_FILE=$FASTDDS_CONFIG" >> /etc/profile.d/ros2.sh
    echo -e "${GREEN}FastDDS configuration created${NC}"
fi

# Test network connectivity
echo ""
echo -e "${GREEN}Testing network connectivity${NC}"

case "$NETWORK_MODE" in
    local)
        echo "Local mode - connectivity OK"
        ;;
    
    distributed)
        # Ping other host
        if [ "$HOST_ROLE" = "pi" ]; then
            OTHER_HOST="192.168.1.20"
            OTHER_NAME="jetson"
        elif [ "$HOST_ROLE" = "jetson" ]; then
            OTHER_HOST="192.168.1.10"
            OTHER_NAME="pi"
        else
            OTHER_HOST=""
        fi
        
        if [ -n "$OTHER_HOST" ]; then
            echo "Testing connectivity to $OTHER_NAME ($OTHER_HOST)..."
            if ping -c 3 "$OTHER_HOST" &> /dev/null; then
                echo -e "${GREEN}✓ Can reach $OTHER_NAME${NC}"
            else
                echo -e "${YELLOW}✗ Cannot reach $OTHER_NAME (may not be online yet)${NC}"
            fi
        fi
        ;;
esac

echo ""
echo -e "${GREEN}=== Network Setup Complete ===${NC}"
echo ""
echo "Next steps:"
echo "1. Verify network configuration: ip addr show"
echo "2. Test ROS 2 discovery: ros2 daemon status"
echo "3. Launch robot: ros2 launch isaac_robot distributed.launch.py deployment:=$DEPLOYMENT"
echo ""
